### ISSUE TITLE
Bug: User Location

### ISSUE THREAD

**Issue by Veeit** [WVV-Crowd-Sourced-Stock-Tracking/Web#29]
Wenn der Nutzer noch zustimmen muss wird anschließend nicht die user location abgefragt. Dies passiert erst nach ein Reload. Tested: Firefox

**Comment by Chaphasilor** [comment]
Firefox Desktop oder Mobile?
Hab das jetzt mit allen Browsern getestet, die ich rumfliegen hatte, also Edge alt&neu, Chrome Mobile, Edge Mobile. Hat überall geklappt, egal wie lang ich gewartet hab...

**Comment by Veeit** [comment]
https://www.icloud.com/iclouddrive/02OeiOr3LYovtLiMrNoUjZaHQ#Screen_Recording_2020-03-24_at_11.42

nutze die firefox developer edition auf macOS, windows scheint aber das gleiche problem zu haben. Google Chrome klappt bei beiden Systemen ohne Probleme

**Comment by Chaphasilor** [comment]
Okay, ich schau mir das später mal an!

**Comment by Chaphasilor** [comment]
Jetzt scheinbar in jedem Browser?

**Comment by Veeit** [comment]
Auf den Handy ja, Desktop nur in Firefox

**Comment by Chaphasilor** [comment]
Try adding a button for requesting user location/location permission

**Comment by Chaphasilor** [comment]
Issue with Firefox seems to be that the location request method immediately returns an error instead of waiting on the user's decision (like Chrome). After granting the permission, the listing will load with the correct location though, at least in the Firefox tablet app for Android...

**Comment by Chaphasilor** [comment]
If the user has turned off GPS in Android, Chrome will not prompt for user location. We should add an info card telling the user to turn on GPS and allow the permission...

**Comment by Chaphasilor** [comment]
Prompting for user location is **still** not working reliably in Safari 🤦‍♂️
